### ISSUE TITLE
"Error: Duplicate CHECK constraint name 'is_bot_check'" when initializing database on MariaDB ≥10.2

### ISSUE THREAD

**Issue by aklapper** [chaoss/grimoirelab-sortinghat#121]
```
$:acko\> mysql -uuser
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 18
Server version: 10.2.12-MariaDB MariaDB Server
MariaDB [(none)]> drop database sortinghat_wm;
Query OK, 4 rows affected (0.09 sec)
MariaDB [(none)]> drop database sortinghat_wm;
ERROR 1008 (HY000): Can't drop database 'sortinghat_wm'; database doesn't exist
MariaDB [(none)]> Bye
$:acko\> sortinghat init sortinghat_wm
Error: Duplicate CHECK constraint name 'is_bot_check' (err: 1826)
$:acko\> grep -r "is_bot_check" .
Binary file ./sortinghat/db/model.pyc matches
./sortinghat/db/model.py:    is_bot = Column(CoerceToBool(name='is_bot_check'), default=False)
./build/lib/sortinghat/db/model.py:    is_bot = Column(CoerceToBool(name='is_bot_check'), default=False)
$:acko\> git show
commit b6f8031174e8e82b7141ea9cfcddc75af9d91d04 (HEAD -> master, origin/master, origin/HEAD)
Merge: 84eceb3 0f66c9d
Author: Santiago Dueñas <sduenas@bitergia.com>
Date:   Tue Feb 13 17:38:11 2018 +0100
```

**Comment by sduenas** [comment]
Weird.

@valeriocos can you check this please, it's related with https://github.com/chaoss/grimoirelab-sortinghat/commit/5f69ed899c94584de17d47b37152098f64012e10

**Comment by valeriocos** [comment]
Hi @aklapper, 

I'm not able to replicate the issue you are reporting.  I followed the same steps (see below) using the native and docker installations.

```
:~/mysql -uroot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 128
Server version: 10.0.33-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

MariaDB [(none)]> drop database sortinghat_wm;
Query OK, 8 rows affected (0.01 sec)

MariaDB [(none)]> drop database sortinghat_wm;
ERROR 1008 (HY000): Can't drop database 'sortinghat_wm'; database doesn't exist

:~/Escritorio$ sortinghat init sortinghat_wm;

git show commit b6f8031174e8e82b7141ea9cfcddc75af9d91d04
Merge: 84eceb3 0f66c9d
Author: Santiago Dueñas <sduenas@bitergia.com>
Date:   Tue Feb 13 17:38:11 2018 +0100
```

**Comment by aklapper** [comment]
For the records, your MariaDB version is way older.

Reverting https://github.com/chaoss/grimoirelab-sortinghat/commit/5f69ed899c94584de17d47b37152098f64012e10 locally (and manually adding the line `from sqlalchemy.types import Boolean`) allows me to work around the problem - I get useless `Error: db assigned` output but the db got initiated as expected at least.

**Comment by aklapper** [comment]
```
$:acko\> rpm -q python2-sqlalchemy
python2-sqlalchemy-1.1.15-1.fc27.x86_64
$:acko\> which python
/usr/bin/python
$:acko\> /usr/bin/python --version
Python 2.7.14
```

**Comment by valeriocos** [comment]
The error appears with MariaDB 10.2, but not with with the versions 10.0 and 10.1. 
In our production environment, we use MariaDB 10.0.

Looking on Internet I found a [bug report](https://bugs.launchpad.net/barbican/+bug/1734329) that could be related to this issue

**Comment by aklapper** [comment]
For the records, https://jira.mariadb.org/browse/MDEV-13508 implies that the problem will be fixed in 10.2.13. Hence closing this task as it's an upstream issue and outside the power of sortinghat's developers.

**Comment by valeriocos** [comment]
thank you @aklapper for the pointer

**Comment by aklapper** [comment]
Sigh. Sorry, I am now on the latest Github checkout of sortinghat and on mariadb-10.2.16-1.fc28.x86_64 and the problem still happens:

```
$:acko\> sortinghat init sortinghat_wm;
Traceback (most recent call last):
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/bin/sortinghat", line 207, in <module>
    code = main()
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/bin/sortinghat", line 101, in main
    code = cmd.run(*args.cmd_args)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/cmd/init.py", line 73, in run
    code = self.initialize(name=params.name, reuse=params.reuse)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/cmd/init.py", line 101, in initialize
    db = Database(user, password, name, host, port)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/db/database.py", line 58, in __init__
    self.__create_schema(self._engine)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/db/database.py", line 167, in __create_schema
    ModelBase.metadata.create_all(engine)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/connections.py", line 852, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/connections.py", line 1053, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/connections.py", line 1336, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/connections.py", line 1010, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/site-packages/PyMySQL-0.7.10-py2.7.egg/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1826, u"Duplicate CHECK constraint name 'is_bot_check'") [SQL: u'\nCREATE TABLE profiles (\n\tuuid VARCHAR(128) NOT NULL, \n\tname VARCHAR(128), \n\temail VARCHAR(128), \n\tgender VARCHAR(32), \n\tgender_acc INTEGER, \n\tis_bot BOOL, \n\tcountry_code VARCHAR(2), \n\tPRIMARY KEY (uuid), \n\tFOREIGN KEY(uuid) REFERENCES uidentities (uuid) ON DELETE CASCADE, \n\tCONSTRAINT is_bot_check CHECK (is_bot IN (0, 1)), \n\tCONSTRAINT is_bot_check CHECK (is_bot IN (0, 1)), \n\tFOREIGN KEY(country_code) REFERENCES countries (code) ON DELETE CASCADE\n)DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci\n\n'] (Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by aklapper** [comment]
Local workaround applied again: Edit `sortinghat/db/model.py` to replace the two calls to `CoerceToBool` by `Boolean`.

**Comment by valeriocos** [comment]
Thank you for reporting this @aklapper . Note that this error does not appear with MariaDB 10.0 (currently used in our production env).

**Comment by rolinge** [comment]
Problem still appears with Version: '10.3.15-MariaDB-1:10.3.15+maria~bionic'.  Would it not be better to fix the code in Sorting Hat as I believe that MySQL is not broken, so they are not going to 'fix' it.

**Comment by aklapper** [comment]
Posting an updated stacktrace here, for discoverability on internet search engines:
```
mariadb-10.3.21-3.fc31.x86_64
python3-3.7.6-1.fc31.x86_64
python3-sqlalchemy-1.3.12-1.fc31.x86_64
sortinghat 0.7.9
```

```
$:acko\> ./bin/sortinghat init sortinghat_wm
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1826, "Duplicate CHECK constraint name 'top_domain_check'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/grimoirelab-sortinghat/sortinghat/bin/sortinghat", line 207, in <module>
    code = main()
  File "~/grimoirelab-sortinghat/sortinghat/bin/sortinghat", line 101, in main
    code = cmd.run(*args.cmd_args)
  File "~/grimoirelab-sortinghat/sortinghat/cmd/init.py", line 73, in run
    code = self.initialize(name=params.name, reuse=params.reuse)
  File "~/grimoirelab-sortinghat/sortinghat/cmd/init.py", line 101, in initialize
    db = Database(user, password, name, host, port)
  File "~/grimoirelab-sortinghat/sortinghat/db/database.py", line 58, in __init__
    self.__create_schema(self._engine)
  File "~/grimoirelab-sortinghat/sortinghat/db/database.py", line 170, in __create_schema
    ModelBase.metadata.create_all(engine)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4316, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2049, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1618, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1826, "Duplicate CHECK constraint name 'top_domain_check'")
[SQL: 
CREATE TABLE domains_organizations (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	domain VARCHAR(128) NOT NULL, 
	is_top_domain BOOL, 
	organization_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT _domain_unique UNIQUE (domain), 
	CONSTRAINT top_domain_check CHECK (is_top_domain IN (0, 1)), 
	CONSTRAINT top_domain_check CHECK (is_top_domain IN (0, 1)), 
	FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE CASCADE
)DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_520_ci

]
(Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by aklapper** [comment]
I wonder if https://stackoverflow.com/questions/20831871/how-to-avoid-inserting-duplicate-entries-when-adding-values-via-a-sqlalchemy-rel might give someone a clue.
