### ISSUE TITLE
to_unicode() throws "TypeError: unicodedata.normalize() argument 2 must be unicode, not str" with Python2

### ISSUE THREAD

**Issue by aklapper** [chaoss/grimoirelab-sortinghat#159]
Using 0.6.9 from today (8dfd61d10d78f27e191f8c805cf73e8980471478), I get:
```
$:acko\> sortinghat load bitergiaexport.json 
Loading unique identities...
Traceback (most recent call last):
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/bin/sortinghat", line 207, in <module>
    code = main()
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/bin/sortinghat", line 101, in main
    code = cmd.run(*args.cmd_args)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/cmd/load.py", line 165, in run
    verbose=params.verbose)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/cmd/load.py", line 271, in import_identities
    reset, verbose)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/cmd/load.py", line 296, in __load_unique_identities
    stored_uuid = self.__load_unique_identity(uidentity, verbose)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/cmd/load.py", line 378, in __load_unique_identity
    identity.username)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/api.py", line 119, in add_identity
    name=name, username=username)
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/utils.py", line 161, in uuid
    to_unicode(name, unaccent=True),
  File "/home/acko/coding/wikimedia/grimoirelab/sortinghat/sortinghat/utils.py", line 115, in to_unicode
    cs = [c for c in unicodedata.normalize('NFD', s)
TypeError: normalize() argument 2 must be unicode, not str
```
That very function is:
```
def to_unicode(x, unaccent=False):
    """Convert a string to unicode"""
    s = str(x)

    if unaccent:
        cs = [c for c in unicodedata.normalize('NFD', s)
              if unicodedata.category(c) != 'Mn']
        s = ''.join(cs)

    return s
```
Environment:
```
python2-2.7.15-2.fc28.x86_64
python2-sqlalchemy-1.2.11-1.fc28.x86_64
mariadb-10.2.16-1.fc28.x86_64
```

**Comment by aklapper** [comment]
https://docs.python.org/2/library/unicodedata.html

https://docs.python.org/2/library/functions.html#str

**Comment by aklapper** [comment]
It isn't, just need to explicitly tell my system. 
Thanks for making me investigate again what's needed to switch to Python3. It took me a while to realize that on Fedora I need the package "python3-PyMySQL" but not the package "python3-mysql". Thanks, works now!
