### ISSUE TITLE
Error inserting identities with emojis data

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#160]
This error is raised when emojis are inserted into the database:

```
$ sortinghat add --username 😂
Traceback (most recent call last):
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'username' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sduenas/devel/venv/bin/sortinghat", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/sduenas/devel/grimoirelab/sortinghat/bin/sortinghat", line 207, in <module>
    code = main()
  File "/home/sduenas/devel/grimoirelab/sortinghat/bin/sortinghat", line 101, in main
    code = cmd.run(*args.cmd_args)
  File "/home/sduenas/devel/grimoirelab/sortinghat/sortinghat/cmd/add.py", line 104, in run
    params.uuid, params.matching, params.interactive)
  File "/home/sduenas/devel/grimoirelab/sortinghat/sortinghat/cmd/add.py", line 151, in add
    new_uuid = api.add_identity(self.db, source, email, name, username, uuid)
  File "/home/sduenas/devel/grimoirelab/sortinghat/sortinghat/api.py", line 137, in add_identity
    return identity_id
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/sduenas/devel/grimoirelab/sortinghat/sortinghat/db/database.py", line 70, in connect
    self.handle_database_error(session, ex)
  File "/home/sduenas/devel/grimoirelab/sortinghat/sortinghat/db/database.py", line 123, in handle_database_error
    raise exception
  File "/home/sduenas/devel/grimoirelab/sortinghat/sortinghat/db/database.py", line 68, in connect
    session.commit()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'username' at row 1") [SQL: 'INSERT INTO identities (id, name, email, username, source, uuid, last_modified) VALUES (%(id)s, %(name)s, %(email)s, %(username)s, %(source)s, %(uuid)s, %(last_modified)s)'] [parameters: {'id': 'dd80c49478131c051ab181be286b3d3f4ad73b02', 'name': None, 'email': None, 'username': '😂', 'source': 'unknown', 'uuid': 'dd80c49478131c051ab181be286b3d3f4ad73b02', 'last_modified': datetime.datetime(2018, 9, 19, 10, 23, 48, 526175)}] (Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by sduenas** [comment]
This error is related to this:

https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

```
MySQL's utf8 permits only the Unicode characters that can be represented with 3 bytes in UTF-8. Here you have a character that needs 4 bytes: \xF0\x90\x8D\x83 (U+10343 GOTHIC LETTER SAUIL).

If you have MySQL 5.5 or later you can change the column encoding from utf8 to utf8mb4. This encoding allows storage of characters that occupy 4 bytes in UTF-8.
```

So we're facing a known problem regarding the configuration of MySQL.
