### ISSUE TITLE
[ui] New warning messages running unit tests

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#325]
Running the UI tests raises some new warning messages.

```
yarn test:unit
yarn run v1.16.0
$ vue-cli-service test:unit
 PASS  tests/unit/queries.spec.js
  ● Console

    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Missing required prop: "getindividuals"
      
      found in
      
      ---> <Individualsdata>
             <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in created hook (Promise/async): "TypeError: Cannot read property 'query' of undefined"
      
      found in
      
      ---> <Individualsdata>
             <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'query' of undefined
          at VueComponent.created (/home/sduenas/devel/grimoirelab/sortinghat/ui/src/components/IndividualsData.vue:24:1)
          at invokeWithErrorHandling (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
          at callHook (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:4207:7)
          at VueComponent.Vue._init (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:4989:5)
          at new VueComponent (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:5134:12)
          at createComponentInstanceForVnode (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:3277:10)
          at init (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:3108:45)
          at createComponent (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
          at createElm (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
          at VueComponent.patch [as __patch__] (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
          at VueComponent.Vue._update (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
          at VueComponent.updateComponent (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
          at Watcher.get (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
          at new Watcher (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
          at mountComponent (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
          at VueComponent.Object.<anonymous>.Vue.$mount (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
          at mount (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/@vue/test-utils/dist/vue-test-utils.js:13518:21)
          at shallowMount (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/@vue/test-utils/dist/vue-test-utils.js:13544:10)
          at Object.test (/home/sduenas/devel/grimoirelab/sortinghat/ui/tests/unit/queries.spec.js:42:21)
          at Object.asyncJestTest (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
          at resolve (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
          at new Promise (<anonymous>)
          at mapper (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
          at promise.then (/home/sduenas/devel/grimoirelab/sortinghat/ui/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
          at process._tickCallback (internal/process/next_tick.js:68:7)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in created hook (Promise/async): "TypeError: Cannot read property 'data' of undefined"
      
      found in
      
      ---> <Individualsdata>
             <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'data' of undefined
          at VueComponent.created (/home/sduenas/devel/grimoirelab/sortinghat/ui/src/components/IndividualsData.vue:25:1)
          at process._tickCallback (internal/process/next_tick.js:68:7)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in created hook (Promise/async): "TypeError: Cannot read property 'data' of undefined"
      
      found in
      
      ---> <Individualsdata>
             <Root>
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property 'data' of undefined
          at VueComponent.created (/home/sduenas/devel/grimoirelab/sortinghat/ui/src/components/IndividualsData.vue:25:1)
          at process._tickCallback (internal/process/next_tick.js:68:7)

 PASS  tests/unit/IndividualCard.spec.js
 PASS  tests/unit/storybook.spec.js

Test Suites: 3 passed, 3 total
Tests:       18 passed, 18 total
Snapshots:   15 passed, 15 total
Time:        6.039s
Ran all test suites.
Done in 8.14s.
```

**Comment by sduenas** [comment]
Closed by #327.
