### ISSUE TITLE
UnicodeEncodeError: surrogates not allowed

### ISSUE THREAD

**Issue by albertinisg** [chaoss/grimoirelab-sortinghat#82]
Got the following error while loading an identity using SH version `0.3.0-4-geedd68e`:
```python
Traceback (most recent call last):
  File "./grimoire_elk/elk/sortinghat.py", line 75, in add_identity
    identity['name'], identity['username'])
  File "/usr/local/lib/python3.4/dist-packages/sortinghat-0.3.1.dev1-py3.4.egg/sortinghat/api.py", line 161, in add_identity
    return identity_id
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/sortinghat-0.3.1.dev1-py3.4.egg/sortinghat/db/database.py", line 59, in connect
    session.commit()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2139, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2223, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1397, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 234, in execute
    args = tuple(map(db.literal, args))
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/connections.py", line 316, in literal
    s = self.escape(o, self.encoders)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/connections.py", line 226, in unicode_literal
    return db.string_literal(str(u).encode(unicode_literal.charset))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce1' in position 7: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce1' in position 127: surrogates not allowed
Call stack:
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "./mordred/task_manager.py", line 94, in run
    task.execute()
  File "./mordred/task_enrich.py", line 143, in execute
    self.__enrich_items()
  File "./mordred/task_enrich.py", line 101, in __enrich_items
    unaffiliated_group=cfg['sortinghat']['unaffiliated_group'])
  File "./grimoire_elk/arthur.py", line 508, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "./grimoire_elk/arthur.py", line 272, in load_identities
    enrich_backend.get_connector_name())
  File "./grimoire_elk/elk/sortinghat.py", line 120, in add_identities
    cls.add_identity(db, identity, backend)
  File "./grimoire_elk/elk/sortinghat.py", line 92, in add_identity
    identity['username'])
Message: 'UnicodeEncodeError. Ignoring it. %s %s %s'
Arguments: ('XXXXXX@mail.com', 'Jorge S\udce1nchez Seijo', None)
2017-04-20 14:33:58,130 - grimoire_elk.elk.enrich - ERROR - UnicodeEncodeError
2017-04-20 14:33:58,130 - grimoire_elk.elk.enrich - ERROR - {'email': 'XXXXXXX@mail.com', 'username': None, 'name': 'Jorge S\udce1nchez Seijo'}
```

**Comment by sduenas** [comment]
This error hasn't been reported again for the new version of SortingHat. We'll open another issue if we find a similar problem.
